---
- hosts: "{{ target | default('localhost') }}"
  become: yes
  roles:
    - nodejs
    - codedeploy

# - src: git@github.com:aptoma/ansible-aws-codedeploy
#   scm: git
#   version: 0.3.0
#   name: aptoma.aws-codedeploy
