---
# tasks file for nodejs
- name: Install nodejs on suse
  community.general.zypper:
    name: nodejs
    state: present
  when: ansible_facts['pkg_mgr'] == "zypper"

- name: Install npm on suse
  community.general.zypper:
    name: npm
    state: present
  when: ansible_facts['pkg_mgr'] == "zypper"

- name: Installing node and npm on Debian/Ubuntu
  yum:
    name: "{{item}}"
    enablerepo: epel
    state: installed
  with_items:
    - nodejs
    - npm
  when: ansible_facts['pkg_mgr'] == "yum"


- name: Create node service on SUSE
  command:
    cmd: sudo npm install pm2@latest -g && pm2 start hello.js && sudo env PATH=$PATH:/usr/bin /usr/local/bin/pm2 startup systemd -u ec2-user --hp /home/ec2-user && pm2 save
    chdir: /home/ec2-user
  when: ansible_facts['pkg_mgr'] == "zypper"
# suse
# community.general.zypper
