---
# tasks file for helloworld

- name: Copying application file
  copy:
    src: helloworld.js
    dest: /home/ec2-user/
    owner: ec2-user
    group: users
    mode: 0644
  notify: restart helloworld #Just executed if any change is done
  when: ansible_facts['pkg_mgr'] == "zypper"

- name: Copying application file
  copy:
    src: helloworld.js
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: 0644
  notify: restart helloworld #Just executed if any change is done
  when: ansible_facts['pkg_mgr'] == "yum"

- name: Copying upstart file
  copy:
    src: helloworld.conf
    dest: /etc/init/helloworld.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_facts['pkg_mgr'] == "yum"

- name: Starting the helloworld node
  service:
    name: helloworld
    state: started
  when: ansible_facts['pkg_mgr'] == "yum"

- name: Starting the helloworld node on SUSE
  ansible.builtin.systemd:
    state: started
    name: pm2-ec2-user
  when: ansible_facts['pkg_mgr'] == "zipper"
