---
# tasks file for helloworld

- name: Copying application file
  copy:
    src: helloworld.js
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: 0644
  notify: restart helloworld #Just executed if any change is done

- name: Copying upstart file
  copy:
    src: helloworld.conf
    dest: /etc/init/helloworld.conf
    owner: root
    group: root
    mode: 0644

- name: Create local directory for git repo to work from
  file:
    path: "{{workdir}}"
    state: directory
    owner: "{{ cron_user }}"
    group: "{{ cron_user }}"
    mode: 0751

- name: Create crontab entry to clone/pull git repository
  template:
    src: templates/etc_cron.d_ansible-pull.j2
    dest: /etc/cron.d/ansible-pull
    owner: "{{ cron_user }}"
    group: "{{ cron_user }}"
    mode: 0644

- name: Create logrotate entry for ansible-pull.log
  template:
    src: templates/etc_logrotate.d_ansible-pull.j2
    dest: /etc/logrotate.d/ansible-pull
    owner: "{{ cron_user }}"
    group: "{{ cron_user }}"
    mode: 0644

- name: Starting the helloworld node
  service:
    name: helloworld
    state: started
